### ISSUE TITLE
[1.16.1] Light Level overlay can be seen through blocks, walls.

### ISSUE THREAD

**Issue by Gbergz** [r8420/MoreOverlays-updated#2] opened 2020-08-03 09:33 UTC
Title^

**Minecraft:** 1.16.1
**Forge:** 32.0.88
**Mod-Version:** 1.18.0

Screenshot Example:
![image](https://user-images.githubusercontent.com/26634554/89168267-e56cdf80-d57c-11ea-86ed-be4970f46128.png)

**-** Gbergz

**Comment by r8420** [comment] 2020-08-04 22:39
This has been fixed in version 1.18.1

**Comment by Bass2style** [comment] 2020-08-12 13:51
sorry to reopen a closed report, but it's also happening on the 1.15 version of the mod, should we see this fixed in 1.15 also please ?

**Comment by r8420** [comment] 2020-08-13 09:56
Will be fixed in the More Overlays version 1.17.4

**Comment by Bass2style** [comment] 2020-08-13 10:12
thank you for your quick support.

**Comment by r8420** [comment] 2020-08-13 11:58
Can you check if the problem is solved in version 1.17.4? 
Link: https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated/files/3031100

**Comment by Bass2style** [comment] 2020-08-14 07:11
still not fixed, it's different, but now it's showing above eveything, you can see the overlay over leaves, and you can see on the mutton on my screenshot that it's also affecting mobs now. xD

https://i.imgur.com/pWeamuK.png

edit : you can also still see the overlay through blocks : 

https://i.imgur.com/VviO7N1.png
https://i.imgur.com/z9zhz3O.png

**Comment by r8420** [comment] 2020-08-14 10:37
Can you tell me which modpack you're playing on? (or a list of the mods if you're not using a modpack)

**Comment by Bass2style** [comment] 2020-08-14 12:53
i use a custom modpack, you can find my modlist here : https://pastebin.com/gaJnZkpV

**Comment by r8420** [comment] 2020-08-14 17:45
Thanks, but what is the modpack called and where can I download it. I need to replicate the issue

**Comment by Bass2style** [comment] 2020-08-14 21:40
it's not availlable on CurseForge or other, but i can export it and give you the instance to import.

edit : i noticed something strange, i think that GDL made something weird, my mod whasn't updated, i still have 1.17.3 installed, soooo, it seems logic that's not fixed, if the mod is not updated. i updated the jar in my instance now, i'm testing later, it's 2AM here, so i'm going to sleep. xD editing this back when done. ^^

edit 2 : okay, it's definitly fixed in 1.17.4, i think GDLauncher failled to update the mod, and i stayd on the 1.17.3 release. sorry for wasting your time for this problem.

also, thanks for fixing the light overlay.

**Comment by r8420** [comment] 2020-08-15 22:39
Great, I will close this issue again then. Let me know if you find any other strange issues with the mod.

**Closed as completed by r8420** 2020-08-15 22:39 UTC
Labels: bug
