### ISSUE TITLE
[1.18.2] Searching Inventory with JEI doesn't work but everything else does

### ISSUE THREAD

**Issue by Epicjii** [r8420/MoreOverlays-updated#35] opened 2022-07-30 02:34 UTC
More overlays version - 1.20.5-mc1.18.1
JEI version - 1.18.2-9.7.1.232

I cannot currently search my inventory with this version of more overlays, but everything else works. 
this is my log:
https://paste.ee/p/qKDsl

Let me know if you need anymore info!

**Comment by copygirl** [comment] 2022-07-31 15:29
Getting the same issue. Here is an excerpt from Epicjii's log that is likely the cause of search not working:
```
[22:26:39] [Render thread/ERROR] [MoreOverlays/]: Something went wrong. Tried to load JEI Search Text Field object
java.lang.NoSuchFieldException: searchField
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at TRANSFORMER/moreoverlays@1.20.5-mc1.18.1/at.ridgo8.moreoverlays.itemsearch.JeiModule.updateModule(JeiModule.java:33)
	at TRANSFORMER/moreoverlays@1.20.5-mc1.18.1/at.ridgo8.moreoverlays.itemsearch.GuiHandler.onGuiInit(GuiHandler.java:30)
	[...]
```

**Comment by WFPhantom** [comment] 2022-08-03 17:00
I think this is due JEI updating and changing core stuff, maybe if you go to an earlier version of JEI its going to work.

**Comment by Jayryn** [comment] 2022-08-05 15:02
@WFPhantom @copygirl @Epicjii Your issue is fixed with #38. We have to wait until @r8420 will merge it.

**You can use my current release for 1.19 which is exactly the same as in the PR.**
https://github.com/drjayy/MoreOverlays-updated/releases/tag/v1.21.2

-> Please leave this issue open so it is used as reference for the PR (aka r8420 will see it)

**Comment by copygirl** [comment] 2022-08-05 19:25
Will there be a bugfix release for 1.18.2? The PR appears to be targeting 1.19 only.

**Comment by Jayryn** [comment] 2022-08-05 20:00
> Will there be a bugfix release for 1.18.2? The PR appears to be targeting 1.19 only.

I could make one but don't expect it to be this quickly, I can take a look at it later if you want.
-> Likely the same issues as 1.18.2 is still supported by Forge as well as JEI so they just implement all newer changes


**EDIT:** My dev environment is currently doing some sketchy stuff which means I'm unable to update 1.18.2 right now

BUT

From what I've discovered, I found out that the 1.18.2 Forge API seems to be fine with older mods are only implement in 1.19+.

However, I did not seem to find an issue with JEI or MoreOverlays at first. Are you completely sure that no other mod is interfering with these 2? It could also be a change in versions which aren't usable together anymore which I didn't test yet.

**Comment by Jayryn** [comment] 2022-08-05 21:53
Like Phantom said, you may want to revert to an older version of JEI for now, but I will test it later on.

**Comment by Jayryn** [comment] 2022-08-05 22:28
@Epicjii and @copygirl you both seem to be using the outdated resource of 1.18.1 for 1.18.2. 
I've done some testing and found out that the latest Forge Release works perfectly fine with latest 1.18.2 JEI Release as well as 1.18.2 MoreOverlays-Updated Release

**Please Update your Mod Resources to contain at least:**
> Minimum Forge Requirement of 40.1.69 (Latest 1.18.2) [Download Forge 40.1.69](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.18.2.html)
- JEI (Just Enough Items) 10.1.3.240 (Latest Forge 1.18.2) [Download JEI 10.1.3.240](https://www.curseforge.com/minecraft/mc-mods/jei/files/3904349)
- MoreOverlays-Updated 1.20.6 (Forge 1.18.2 Release) [Download MoreOverlays 1.20.6](https://github.com/r8420/MoreOverlays-updated/releases/tag/1.20.6-mc1.18.2)

**Keep me updated once you tested your environment with these requirements.**

**Comment by copygirl** [comment] 2022-08-06 05:13
JEI 10 is not supported by a bunch of mods, so we can't use it. It's an **alpha** release so that's a pretty big indication that it shouldn't be used by your average user. It would be nice if MoreOverlays would target a stable version of JEI for 1.18.

We're using `moreoverlays-1.20.5-mc1.18.1.jar`, which is however marked as compatible with `1.18.2` on CurseForge.

**Comment by Jayryn** [comment] 2022-08-06 06:09
> JEI 10 is not supported by a bunch of mods, so we can't use it. It's an **alpha** release so that's a pretty big indication that it shouldn't be used by your average user. It would be nice if MoreOverlays would target a stable version of JEI for 1.18.
> 
> We're using `moreoverlays-1.20.5-mc1.18.1.jar`, which is however marked as compatible with `1.18.2` on CurseForge.

You may want to try the newer version of MoreOverlays though, as no other mod depends on it

**Please keep in mind that I am not a maintainer of this resource and will not see forward to do it.**

-> The requirements I posted were only for testing purposes, to see if everything worked fine in a close environment.

I can test out several JEI versions later.

**Comment by copygirl** [comment] 2022-08-06 06:38
I went ahead and installed Just Enough Items `10.1.3.240` and MoreOverlays-Updated `1.20.6-mc1.18.2` with our current set of mods and I still get an error ("Something went wrong. Tried to load JEI Search Text Field object") and can't use the search field to highlight items. However, I also am missing entire sets of recipe types that don't show up in JEI, presumably due to the API changes in said version breaking many mods.

I hope I don't come across as demanding. I just want to record my findings, and suggest that there should be a stable version of the mod that works out of the box with latest (stable) versions of other mods.

**Comment by Jayryn** [comment] 2022-08-06 07:35
@copygirl could you provide a crash log please? **The Full Log (No Snippets please)**

**MoreOverlays-Updated 1.20.6 is dependent on JEI 10.1.0.202+**

I've also tested out some versions of JEI with MoreOverlays and found out that JEI only supports 10.1.0.198+ for Mod Dependency Usage in 1.18.2 by the time that I am writing this.

-> I may test a little stuff and bump the JEI dependency version up a little if necessary 

![image](https://user-images.githubusercontent.com/77808206/183239501-afb7540f-0b3b-4a46-95b7-62bfdef9288b.png)

**Comment by copygirl** [comment] 2022-08-06 08:12
There is no crash, and the `latest.log`, due to the log spam caused by the JEI incompatibility the file is over 40 MiB and over 390k lines. PolyMC even stops its own logger and warns about disk space usage. The spam seems to boil down to `[mezz.jei.common.util.IngredientSupplierHelper/]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: [...] java.lang.NoSuchFieldError: FLUID` (obvious API breakage) with multiple mods such as Botania, Tinkers' Construct, Thermal Series, Immersive Engineering, ... Which to me just appears as a clear indication that JEI 10 is not ready or maybe was never intended to be used.

If you really do care about the full log file, let me know where I can upload it.

**Comment by Jayryn** [comment] 2022-08-06 08:50
welp @copygirl, I know what the issue is and its fixed locally but now I'm completely bamboozled why the hell it works in 1.19 xD

**EDIT:** I will publish the resource in a moment

**Comment by Jayryn** [comment] 2022-08-06 09:07
@copygirl @Epicjii You issue will be fixed with #39.

-> JEI just thought `**We're going to make renaming changes the newest 1.18.2 versions and revert them back in 1.19**`

**This Resource requires at least**
- Forge 1.18.2 above 40.1.0
- JEI (Just Enough Items) above 10.1.3.238

**You can download the generated resource under**
>Please keep in mind that this resource will not get maintained in my fork
https://github.com/drjayy/MoreOverlays-updated/releases/tag/v1.20.7

**Comment by Jayryn** [comment] 2022-08-06 17:15
Does everything work for you @copygirl and @Epicjii ?

**Comment by copygirl** [comment] 2022-08-06 17:36
@drjayy I can't test at this time, but I do want to note that I can't use JEI 10 with my current modset anyway so even if the search field issue is fixed, JEI is practically unusable. We have to stick to JEI 9.

**Comment by Jayryn** [comment] 2022-08-06 19:42
> @drjayy I can't test at this time, but I do want to note that I can't use JEI 10 with my current modset anyway so even if the search field issue is fixed, JEI is practically unusable. We have to stick to JEI 9.

That's sad to hear, I could only provide a short fix for it as I need to import JEI directly instead of loading it from official sources
(JEI themselves don't support modding below 10)

**Comment by Jayryn** [comment] 2022-08-06 20:32
Ignore the part above, I've just looked in the wrong place for it xD

I will make a source using JEI 9 as soon as I can, but I'm currently not at home to do it @copygirl

**Comment by r8420** [comment] 2022-08-06 22:10
I'm working on it.

**Comment by r8420** [comment] 2022-08-06 23:49
I've released 2 versions that hopefully fixes this issue:

MoreOverlays 1.20.8 (Alpha): for JEI 10.1.0.228 or higher
MoreOverlays 1.20.7: for JEI 9.7.0.229 or higher (but not JEI 10)

**Closed as completed** 2022-08-08 15:38 UTC
